export class JetsnackColor {
  static readonly Shadow11: string = '#FF001787';
  static readonly Shadow10: string = '#FF00119E';
  static readonly Shadow9: string = '#FF0009B3';
  static readonly Shadow8: string = '#FF0200C7';
  static readonly Shadow7: string = '#FF0E00D7';
  static readonly Shadow6: string = '#FF2A13E4';
  static readonly Shadow5: string = '#FF4B30ED';
  static readonly Shadow4: string = '#FF7057F5';
  static readonly Shadow3: string = '#FF9B86FA';
  static readonly Shadow2: string = '#FFC8BBFD';
  static readonly Shadow1: string = '#FFDED6FE';
  static readonly Shadow0: string = '#FFF4F2FF';

  static readonly Ocean11: string = '#FF005687';
  static readonly Ocean10: string = '#FF006D9E';
  static readonly Ocean9: string = '#FF0087B3';
  static readonly Ocean8: string = '#FF00A1C7';
  static readonly Ocean7: string = '#FF00B9D7';
  static readonly Ocean6: string = '#FF13D0E4';
  static readonly Ocean5: string = '#FF30E2ED';
  static readonly Ocean4: string = '#FF57EFF5';
  static readonly Ocean3: string = '#FF86F7FA';
  static readonly Ocean2: string = '#FFBBFDFD';
  static readonly Ocean1: string = '#FFD6FEFE';
  static readonly Ocean0: string = '#FFF2FFFF';

  static readonly Lavender11: string = '#FF170085';
  static readonly Lavender10: string = '#FF23009E';
  static readonly Lavender9: string = '#FF3300B3';
  static readonly Lavender8: string = '#FF4400C7';
  static readonly Lavender7: string = '#FF5500D7';
  static readonly Lavender6: string = '#FF6F13E4';
  static readonly Lavender5: string = '#FF8A30ED';
  static readonly Lavender4: string = '#FFA557F5';
  static readonly Lavender3: string = '#FFC186FA';
  static readonly Lavender2: string = '#FFDEBBFD';
  static readonly Lavender1: string = '#FFEBD6FE';
  static readonly Lavender0: string = '#FFF9F2FF';

  static readonly Rose11: string = '#FF7F0054';
  static readonly Rose10: string = '#FF97005C';
  static readonly Rose9: string = '#FFAF0060';
  static readonly Rose8: string = '#FFC30060';
  static readonly Rose7: string = '#FFD4005D';
  static readonly Rose6: string = '#FFE21365';
  static readonly Rose5: string = '#FFEC3074';
  static readonly Rose4: string = '#FFF4568B';
  static readonly Rose3: string = '#FFF985AA';
  static readonly Rose2: string = '#FFFDBBCF';
  static readonly Rose1: string = '#FFFED6E2';
  static readonly Rose0: string = '#FFFFF2F6';

  static readonly Neutral8: string = '#FF121212';
  static readonly Neutral7: string = '#DE000000';
  static readonly Neutral6: string = '#99000000';
  static readonly Neutral5: string = '#61000000';
  static readonly Neutral4: string = '#1F000000';
  static readonly Neutral3: string = '#1FFFFFFF';
  static readonly Neutral2: string = '#61FFFFFF';
  static readonly Neutral1: string = '#BDFFFFFF';
  static readonly Neutral0: string = '#FFFFFFFF';

  static readonly FunctionalRed: string = '#FFD00036';
  static readonly FunctionalRedDark: string = '#FFEA6D7E';
  static readonly FunctionalGreen: string = '#FF52C41A';
  static readonly FunctionalGrey: string = '#FFF6F6F6';
  static readonly FunctionalDarkGrey: string = '#FF2E2E2E';

  static readonly AlphaNearOpaque: number = 0.95;
}
